### ISSUE TITLE
new yahoo website format broke the python soup routine

### ISSUE THREAD

**Issue by techbackpack** [boyank/yahoo_options#4]
It appears the new yahoo website design has caused the Soup parse to break.  Hopefully this is not a difficult repair.  Please let me know.

**Comment by boyank** [comment]
Thanks for letting me know, as I don't use the script on a daily basis. Will check what the problem is.

**Comment by boyank** [comment]
It looks like the new yahoo website uses javascript to populate the data. It will take some time to rewrite the script given the new site, i.e. new different approach, not a simple fix. So I cannot promise any deadline.

**Comment by techbackpack** [comment]
Understandable.  I just wanted to let you know since their structure changed around.

**Comment by boyank** [comment]
fixed. now it's possible to get the data in json format no need to use BeautifulSoup to screen-scrape the site.
json has a lot more data than previously  available. I will update the README.md

**Comment by techbackpack** [comment]
great work.  thanks boyank.
