### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by petercerno** [boyank/yahoo_options#5]
Hi, in the method `get_json_data` you should use:

```
chain_json = json.loads(urllib.request.urlopen(url).read().decode('utf-8'))
```

instead of 

```
chain_json = json.load(urllib.request.urlopen(url))
```

to work properly in Python 3.5.

Cheers,

Peter

**Comment by boyank** [comment]
Thank you for your feedback.  I will look into it. I think json.loads should work the same in both 2 and 3. Moreover python3 has native unicode support. Is it a problem you have for specific ticker and if yes - which one, so I could test myself?

**Comment by petercerno** [comment]
Note that in your code you are using `json.load`, not `json.loads`. I have tested your code in Python 3.5 with the ticker `GDX` (but it probably does not matter) and it did not work. It got fixed when I applied my fix.

**Comment by boyank** [comment]
yeah. That's why i thought a file-like object should work fine (i.e. load vs loads). But after your comment I've found that urllib opens it in a byte mode. There is discussion on SO.  I will fix it. Also maybe it's time to refactor it using requests. Thanks.
